[project]
name = "EyeSim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
        'gymnasium',
        'box2d_py',
        'numpy',
        'matplotlib',
        'scikit-image',
]
